### ISSUE TITLE
Add search to CMS

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/cambium#26]
Need to consider various database adapters. Ideally this is some method set in the model, and the CMS comes with a view that breaks up search results by model type.

**Comment by tomstuder** [comment]
Recent request from FNF was to have search word completion or more robust search. 

If a user starts to type  "so ..." The search field could offer possible terms, products or content on the site (ex. "Soup", "solution", "soluble", etc) basically a "suggestive search" feature.

If you come across a gem, this may be a nice future feature.

**Comment by hungrymedia** [comment]
Limiting to PGSearch for now.

**Comment by seancdavis** [comment]
Thanks, @hungrymedia!

Instead of providing the ability to customize results here (although we will eventually), we should break up the results by *model*, and then figure out the correct edit links.
