### ISSUE TITLE
CMS Dashboard

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/cambium#28]
Consider using Paper Trail and using dashboard as an activity log.

And consider using [Chart.js](http://www.chartjs.org/docs/) for rendering any charts on the dashboard. It's nice and easy to use.

**Comment by hungrymedia** [comment]
@seancdavis PaperTrail and a default dashboard view of all versions has been added. Just a simple heading and table for now. Let's discuss where else it should go from here.
