### ISSUE TITLE
Make page hierarchy accessible in the UI

### ISSUE THREAD

**Issue by hungrymedia** [seancdavis/cambium#40]
* Add hierarchical_title (e.g. Products: Sexy Garbage Man Costume)
* ensure has_ancestry plugin is added to pages model (currently pages are not responding to ancestry helpers, like _.children_)

**Comment by seancdavis** [comment]
@hungrymedia: I've thought about this a bit. I'm thinking the default indication of depth could be determined by a `page_path` attribute, which could take into account its parents.

I don't mind adding this presenter method on pages, but might be more useful to surface the page path in the admin.
